name: ETCCDI_precipitacion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - cdo
  - numpy
  - scipy
  - matplotlib<3.8      # ← solo el límite superior, no versión exacta
  - netcdf4
  - pyyaml
  - pandas
  - pyproj
  - cartopy
  - jupyterlab
  - ipykernel
  - ipympl
  - pip:
    - proplot==0.9.7    # ← proplot vía pip para evitar conflictos conda
    - tqdm
    - pymannkendall
