name: ETCCDI_precipitacion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - cdo
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pyyaml
  - pandas
  - pyproj
  - cartopy
  - jupyterlab
  - ipykernel
  - ipympl
  - xarray
  - openpyxl
  - pip:
    - tqdm
    - pymannkendall
