name: ETCCDI_precipitacion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9        # ← cambiado de 3.10 a 3.9
  - pip
  - cdo
  - numpy
  - scipy
  - matplotlib=3.7    # compatible con python 3.9
  - proplot=0.9.7
  - netcdf4
  - pyyaml
  - pandas
  - pyproj
  - cartopy
  - jupyterlab
  - ipykernel
  - ipympl
  - pip:
    - tqdm
    - pymannkendall
